### ISSUE TITLE
Error when manually adding FLOAT to wallet

### ISSUE THREAD

**Issue by mattsorber** [muttoni/float#40]
I'm an event admin and I've been trying to manually award a user's wallet to distribute a FLOAT to them. Our FLOAT was active through 4pm CST today, and I've trying to distribute subsequent to that. I first tried to distribute directly to Dapper wallet, then I had the user connect their Dapper wallet, then I created a whole new event and attempted to manually add a duplicate FLOAT to them that way. The transaction made it's way up to executed every time and then produced the error:  "Error: Could not get the public FLOAT Collection from the recipient. | 47 | ?? panic("Could not get the public FLOAT Collection from the recipient.") | ^^^^^^^". I tried pausing and resuming claiming on both the initial and duplicate event, but continued to receive the error message nonetheless.

**Comment by jacob-tucker** [comment]
Hey there! 

This error actually happens when the receiving user has not set up their FLOAT Collection. They have to go to https://floats.city/, click on their account in the top right, and click “Initialize Account” (it may be “Setup Account”), I can’t quite remember. Once they do that, they no longer have to do it anymore
